### ISSUE TITLE
Add default behavior for docker.certPath if default behavior for docker.url is used

### ISSUE THREAD

**Issue by ebelisle** [bmuschko/gradle-docker-plugin#327]
I like the behavior added by #310 where docker.url will default to System.env.DOCKER_HOST when DOCKER_HOST is set, or unix:///var/run/docker.sock when DOCKER_HOST is not set.

When docker.url and docker.certPath are not specified, I would like default behavior for docker.certPath.  My current workaround is:

```groovy
docker {
    certPath = url.startsWith('tcp://') ? new File("$System.env.DOCKER_CERT_PATH") : null
}
```

**Comment by cdancy** [comment]
I actually meant to do something similar for `DOCKER_CERT_PATH` but it slipped my mind before we released. I'll get this knocked out for next release.

**Comment by aol-nnov** [comment]
@cdancy it's 3.2.4 now, but certPath is still not picked from system env!

any plans on this issue?

**Comment by cdancy** [comment]
@aol-nnov send in a PR, as it's a quick enough fix, and i'll get it in the next release which is going out sooner rather than later! It's one of those things that always slips my mind.
